<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="api-base" content="{{ url('/api/v1') }}"><meta name="verification-url" content="{{ route('job.verification') }}"><meta name="login-url" content="{{ route('login') }}">
<title>Fixifier Plus | Job Verification</title><link rel="stylesheet" href="{{ asset('css/job-verification.css') }}"><script src="{{ asset('js/job-verification.js') }}" defer></script>
</head><body>
<header><div class="nav"><div class="brand">fixifier<span> plus</span></div><span class="pill" id="portalLabel">JOB VERIFICATION</span></div></header>
<main class="wrap"><div class="intro"><div><div class="muted"><a href="{{ route('portal') }}">Dashboard</a> / Job verification</div><h1>Review your completed repair</h1><div class="muted">Compare evidence, approve work, or request support.</div></div><span class="pill" id="headerStatus">Loading…</span></div>
<div id="pageMessage" class="notice" role="status" aria-live="polite">Loading your bookings…</div><div id="picker" class="card hidden"></div>
<div class="layout hidden" id="bookingLayout"><aside class="card sidebar" aria-label="Dashboard sections"><button class="active" data-tab="review">📷 Job evidence</button><button data-tab="history">🕒 Job timeline</button><button data-tab="disputes">⚖️ Dispute center</button><button data-tab="payments">💳 Payment status</button></aside><div>
<section class="section active" id="review"><div class="card"><div class="topline"><div><div class="muted" id="reference"></div><h2 id="service"></h2><div class="muted" id="technician"></div></div><span class="tag" id="jobTag"></span></div><hr class="divider">
<div class="statrow"><div class="stat">Service charge<strong id="charge">—</strong></div><div class="stat">Evidence<strong id="stageCount">—</strong></div><div class="stat">Job date<strong id="jobDate">—</strong></div></div>
<h3>Before &amp; after evidence</h3><p class="muted">Records uploaded for this booking.</p><div class="grid"><div><p class="photo-label">BEFORE · Initial condition</p><div id="beforePhotos"></div><p class="muted" id="description"></p></div><div><p class="photo-label">AFTER · Completed repair</p><div id="afterPhotos"></div></div></div>
<div class="notice">Evidence belongs to this booking. Images alone do not verify authenticity.</div><h3>Technician completion note</h3><div id="completionNote"></div>
<div class="actions hidden" id="reviewActions"><button class="btn" id="approveBtn">Approve completed work</button><button class="btn danger" id="disputeBtn">Raise a dispute</button></div><div class="notice" id="resultMessage" role="status"></div>
</div></section>
<section class="section" id="history"><div class="card"><h2>Job timeline</h2><p class="muted">Recorded timestamps available for this booking.</p><ol class="timeline" id="timeline"></ol></div></section>
<section class="section" id="disputes"><div class="card"><h2>Dispute center</h2><p class="muted">If the repair is incomplete or evidence does not match the work, submit a case for review.</p><div id="disputeDetails"></div><button class="btn danger hidden" id="disputePageBtn">Open dispute form</button></div></section>
<section class="section" id="payments"><div class="card"><h2>Payment status</h2><div class="statrow"><div class="stat">Service total<strong id="paymentTotal">—</strong></div><div class="stat">Provider<strong style="font-size:16px" id="provider">—</strong></div><div class="stat">Recorded state<strong style="font-size:16px" id="settlement">—</strong></div></div><div class="notice" id="paymentNotice"></div></div></section>
</div></div></main>
<div class="modal-backdrop hidden" id="modal" role="dialog" aria-modal="true" aria-labelledby="modalTitle"><div class="modal"><h2 id="modalTitle">Confirm action</h2><div id="approveContent" class="hidden"><p>Confirm that the repair is satisfactory and you have reviewed the submitted evidence.</p><div class="notice">This records your approval. It does not initiate a payment-provider transfer.</div><div class="actions"><button class="btn" id="confirmApprove">Confirm approval</button><button class="btn secondary" data-close>Cancel</button></div></div>
<form id="disputeForm" class="hidden"><p class="muted">Describe the issue so Fixifier support can review it.</p><div class="field"><label for="reason">Reason</label><select id="reason" required><option value="">Select a reason</option><option>Repair incomplete</option><option>Issue persists</option><option>Photos do not match the work</option><option>Property damage</option><option>Other concern</option></select></div><div class="field"><label for="details">Description</label><textarea id="details" required minlength="20" maxlength="5000" placeholder="Explain what happened (at least 20 characters)"></textarea></div><div class="field"><label for="supportPhoto">Supporting photo</label><input type="file" id="supportPhoto" disabled><small class="muted">Dispute photo attachments are not available yet.</small></div><div class="actions"><button class="btn danger" type="submit">Submit dispute</button><button class="btn secondary" type="button" data-close>Cancel</button></div></form><p id="actionError" class="notice hidden" role="alert"></p></div></div>
<footer class="foot">Fixifier Plus · Booking verification</footer></body></html>
