<?php
namespace App\Http\Controllers\Api\V1;
use App\Enums\BookingStatus; use App\Http\Controllers\Controller; use App\Http\Requests\SubmitQuotationRequest; use App\Models\{Booking,Dispute,JobEvidence,Payment,Quotation}; use App\Services\Audit; use Illuminate\Http\{JsonResponse,Request}; use Illuminate\Support\Facades\{DB,Storage};
class WorkflowController extends Controller {
 public function quote(SubmitQuotationRequest $r,Booking $b):JsonResponse{abort_unless($b->technician_id===$r->user()->id&&$b->status===BookingStatus::Requested,409);$q=Quotation::updateOrCreate(['booking_id'=>$b->id],$r->validated());$b->update(['status'=>BookingStatus::Quoted]);Audit::record('quotation.submitted',$q);return response()->json(['data'=>$q],201);}
 public function accept(Request $r,Booking $b):JsonResponse{abort_unless($b->customer_id===$r->user()->id&&$b->status===BookingStatus::Quoted,409);DB::transaction(function()use($b){$b->quotation()->lockForUpdate()->firstOrFail()->update(['accepted_at'=>now()]);$b->update(['status'=>BookingStatus::Confirmed]);});Audit::record('quotation.accepted',$b);return response()->json(['data'=>$b->fresh()]);}
 public function start(Request $r,Booking $b):JsonResponse{abort_unless($b->technician_id===$r->user()->id&&$b->status===BookingStatus::Confirmed,409);$b->update(['status'=>BookingStatus::InProgress]);Audit::record('booking.started',$b);return response()->json(['data'=>$b]);}
 public function evidence(Request $r,Booking $b):JsonResponse{abort_unless($b->technician_id===$r->user()->id&&$b->status===BookingStatus::InProgress,409);$data=$r->validate(['type'=>'required|in:before,after','photo'=>'required|image|mimes:jpg,jpeg,png,webp|max:10240','note'=>'nullable|string|max:2000','captured_at'=>'required|date|before_or_equal:now']);$file=$data['photo'];$path=$file->store("bookings/{$b->id}/evidence",'private');$e=JobEvidence::create(['booking_id'=>$b->id,'technician_id'=>$r->user()->id,'type'=>$data['type'],'storage_path'=>$path,'mime_type'=>$file->getMimeType(),'size_bytes'=>$file->getSize(),'sha256'=>hash_file('sha256',$file->getRealPath()),'note'=>$data['note']??null,'captured_at'=>$data['captured_at']]);Audit::record('evidence.uploaded',$e,['type'=>$e->type]);return response()->json(['data'=>$e],201);}
 public function submitEvidence(Request $r,Booking $b):JsonResponse{abort_unless($b->technician_id===$r->user()->id&&$b->status===BookingStatus::InProgress,409);$types=$b->evidence()->distinct()->pluck('type');abort_unless($types->contains('before')&&$types->contains('after'),422,'Before and after evidence are both required.');$b->update(['status'=>BookingStatus::EvidenceSubmitted]);Audit::record('evidence.submitted',$b);return response()->json(['data'=>$b]);}
 public function viewEvidence(Request $r,JobEvidence $e):JsonResponse{$b=$e->booking;abort_unless($r->user()->role->value==='admin'||$b->customer_id===$r->user()->id||$b->technician_id===$r->user()->id,403);return response()->json(['data'=>$e,'download_url'=>Storage::disk('private')->temporaryUrl($e->storage_path,now()->addMinutes(10))]);}
 public function approve(Request $r,Booking $b):JsonResponse{abort_unless($b->customer_id===$r->user()->id&&$b->status===BookingStatus::EvidenceSubmitted,409);abort_unless($b->payment()->where('status','authorized')->exists(),409,'Payment must be authorized before approval.');DB::transaction(function()use($b){$b->lockForUpdate()->update(['status'=>BookingStatus::Completed]);$b->payment()->where('status','authorized')->update(['status'=>'released','released_at'=>now()]);});Audit::record('booking.approved',$b);return response()->json(['data'=>$b->fresh()]);}
 public function dispute(Request $r,Booking $b):JsonResponse{abort_unless($b->customer_id===$r->user()->id&&$b->status===BookingStatus::EvidenceSubmitted,409);$data=$r->validate(['reason'=>'required|string|max:120','details'=>'required|string|min:20|max:5000']);$d=DB::transaction(function()use($b,$r,$data){$b->lockForUpdate()->update(['status'=>BookingStatus::Disputed]);return Dispute::create($data+['booking_id'=>$b->id,'opened_by'=>$r->user()->id,'status'=>'open']);});Audit::record('dispute.opened',$d);return response()->json(['data'=>$d],201);}
 public function resolve(Request $r,Dispute $d):JsonResponse{abort_unless($r->user()->role->value==='admin'&&$d->status==='open',403);$data=$r->validate(['decision'=>'required|in:release,refund,rework','resolution'=>'required|string|min:20|max:5000']);DB::transaction(function()use($d,$r,$data){$d->update(['status'=>'resolved','resolution'=>$data['resolution'],'resolved_by'=>$r->user()->id,'resolved_at'=>now()]);$status=$data['decision']==='release'?BookingStatus::Completed:($data['decision']==='rework'?BookingStatus::InProgress:BookingStatus::Cancelled);$d->booking()->update(['status'=>$status]);if($data['decision']==='release')$d->booking->payment()->update(['status'=>'released','released_at'=>now()]);if($data['decision']==='refund')$d->booking->payment()->update(['status'=>'refunded','refunded_at'=>now()]);});Audit::record('dispute.resolved',$d,['decision'=>$data['decision']]);return response()->json(['data'=>$d->fresh()]);}
}
