<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void {
 Schema::create('users',function(Blueprint $t){$t->id();$t->string('name');$t->string('email')->unique();$t->string('phone')->nullable()->unique();$t->string('password');$t->string('role',24)->index();$t->timestamp('email_verified_at')->nullable();$t->rememberToken();$t->timestamps();});
 Schema::create('technician_profiles',function(Blueprint $t){$t->id();$t->foreignId('user_id')->unique()->constrained()->cascadeOnDelete();$t->string('trade');$t->text('bio')->nullable();$t->unsignedSmallInteger('years_experience')->default(0);$t->string('kyc_status',24)->default('pending')->index();$t->timestamp('verified_at')->nullable();$t->timestamps();});
 Schema::create('bookings',function(Blueprint $t){$t->id();$t->string('reference')->unique();$t->foreignId('customer_id')->constrained('users');$t->foreignId('technician_id')->nullable()->constrained('users');$t->string('service_category')->index();$t->text('description');$t->text('address');$t->timestampTz('scheduled_at')->nullable();$t->string('status',32)->default('requested')->index();$t->timestampsTz();$t->index(['customer_id','status']);$t->index(['technician_id','status']);});
 Schema::create('quotations',function(Blueprint $t){$t->id();$t->foreignId('booking_id')->unique()->constrained()->cascadeOnDelete();$t->unsignedBigInteger('amount_minor');$t->char('currency',3)->default('NGN');$t->text('scope');$t->timestampTz('expires_at');$t->timestampTz('accepted_at')->nullable();$t->timestampsTz();});
 Schema::create('job_evidence',function(Blueprint $t){$t->id();$t->foreignId('booking_id')->constrained()->cascadeOnDelete();$t->foreignId('technician_id')->constrained('users');$t->string('type',12);$t->text('storage_path');$t->string('mime_type',100);$t->unsignedBigInteger('size_bytes');$t->char('sha256',64);$t->text('note')->nullable();$t->timestampTz('captured_at');$t->timestampsTz();$t->index(['booking_id','type']);});
 Schema::create('disputes',function(Blueprint $t){$t->id();$t->foreignId('booking_id')->unique()->constrained()->cascadeOnDelete();$t->foreignId('opened_by')->constrained('users');$t->string('reason');$t->text('details');$t->string('status',24)->default('open')->index();$t->text('resolution')->nullable();$t->foreignId('resolved_by')->nullable()->constrained('users');$t->timestampTz('resolved_at')->nullable();$t->timestampsTz();});
 Schema::create('payments',function(Blueprint $t){$t->id();$t->foreignId('booking_id')->unique()->constrained()->cascadeOnDelete();$t->string('provider');$t->string('provider_reference')->unique();$t->unsignedBigInteger('amount_minor');$t->char('currency',3)->default('NGN');$t->string('status',24)->index();$t->timestampTz('authorized_at')->nullable();$t->timestampTz('released_at')->nullable();$t->timestampTz('refunded_at')->nullable();$t->timestampsTz();});
 Schema::create('audit_events',function(Blueprint $t){$t->bigIncrements('id');$t->foreignId('actor_id')->nullable()->constrained('users')->nullOnDelete();$t->string('action')->index();$t->string('subject_type');$t->unsignedBigInteger('subject_id');$t->json('metadata')->nullable();$t->ipAddress('ip_address')->nullable();$t->timestamp('created_at')->useCurrent();$t->index(['subject_type','subject_id']);});
 } public function down():void {foreach(['audit_events','payments','disputes','job_evidence','quotations','bookings','technician_profiles','users'] as $table)Schema::dropIfExists($table);} };
